### ISSUE TITLE
Get snapshot of current active contacts

### ISSUE THREAD

**Issue by texasflood** [simbody/simbody#263]
There should be some way of getting information of what contact surface are currently in contact. My thoughts on how to implement this would be to have a function like this:

<code>bool isThereContact (State state, ContactTrackerSubsystem contactSystem, MobilizedBody mobod1, ContactSurface surface1, MobilizedBody mobod2, ContactSurface surface2);</code>

which tells you whether the given unique pair of the contact surface associated with a particular <code>MobilizedBody</code> are currently in contact. As multiple Mobods can use the same <code>ContactSurface</code>, both must be passed to the function.

This would be very helpful to implement some control algorithms which change state based on contacts.

**Comment by sherm1** [comment]
Hi, Anas. PR #347 added a method that maps `(MobilizedBody,contactSurfaceNumber)` to `ContactSurfaceIndex`. There is already a method `ContactSnapshot::hasContact(ContactSurfaceIndex,ContactSurfaceIndex)` that tells you whether a particular pair of surfaces are contacting. So this should now let you do what you wanted to do in the first place. This change is currently in the master branch if you want to try it and will be released in Simbody 3.6.

Thanks for pointing out this problem.

Regards,
Sherm

/cc @texasflood, @hsu
