### ISSUE TITLE
Handling relative paths. Confusion with deconstructPathname

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#264]
I am working on https://github.com/opensim-org/opensim-core/issues/118. @sherm1 , in this issue you claim that

> FYI, Simbody has a utility class SimTK::Pathname that provides platform-independent handling of relative path names so that changing directory isn't required.

Based on the Pathname API, this does not seem possible. So I have been trying to alter Pathname::getAbsolutePathname to suit my needs.

My objective is to take a path `pathname` that is relative an arbitrary path `base`, and express it as either (1) a relative path that is relative to my cwd, or (2) an absolute path.

I made the necessary changes to `getAbsolutePathname` so that it could use a `base` that is not the cwd. However, I misunderstood what `deconstructPathname` does. The documentation contains the confusing statement:

> "." starts an absolute path name which is relative to the current working directory

How can an absolute path be relative to something else? I fed this method a path like `../../myfile` and was told that this is an absolute path. I learned that `deconstructPathname` is trying to do more than it advertises: it converts relative paths to absolute paths if you pass it "keywords" such as `../`, `./`, `@`. So from this perspective, indeed, `./` specifies an absolute path. I feel this is improper; `getAbsolutePathname` should do that; I simply wanted to deconstruct the path as given. 

I believe my current method of trying to do (1) or (2) cannot be done simply by modifying `getAbsolutePathname`. 

@sherm1 does Pathname, as is, provide the functionality I seek? If not, I would like to alter `deconstructPathname` so that it strictly decomposes a given path, and does not try to create an absolute path based on keywords. I'm happy to take other suggestions as well.

**Comment by sherm1** [comment]
Chris, I believe PR #307 has addressed this issue which you opened. Please close if you agree.

**Comment by chrisdembia** [comment]
:fireworks:
