### ISSUE TITLE
Mechanism to invalidate Index member variables upon copy

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#343]
Say you have a MeasureIndex as a member variable in your class. When you copy your class, the index should become invalid. This can be done by writing a copy constructor in which you invalidate the index. Sherm suggested a clean mechanism to do this automatically: create a class that will invalidate your index for you: InvalidateIndexOnCopy<T>, ReferenceIndex<T> (since the functionality is similar to ReferencePtr<T>), or InvalidateOnCopyIndex<T>.

**Comment by sherm1** [comment]
This should get fixed by #359.

**Comment by sherm1** [comment]
@chrisdembia, this issue should also have been fixed by PR #426. Please close if you agree.

**Comment by chrisdembia** [comment]
I'll close the issue once I make use of the new mixin class for indices.
