### ISSUE TITLE
Filling Matrix with initial value incorrectly requesting length() instead of nelt()?

### ISSUE THREAD

**Issue by aseth1** [simbody/simbody#366]
Initializing a matrix fails [here](https://github.com/simbody/simbody/blob/master/SimTKcommon/BigMatrix/src/MatrixHelper.cpp#L774) in debug since 'length()` assumes 1D matrix (row or column Vector).

**Comment by sherm1** [comment]
PR #367 waiting for your review, Ajay. 

BTW, this would also fail for Matrix_<Vec3> or whatever; the only reason it worked for you was that you actually had a 1x4 matrix in your test so the assert in length() was happy.
