### ISSUE TITLE
clang 3.6 warns about rpoly.cpp fabs vs std::abs

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#384]
@klshrinidhi got me trying clang-3.6, which gives the following warning:

```
/Users/chris/repos/simbody/1/simbody/SimTKcommon/Polynomial/src/rpoly.cpp:311:29: warning: 
      absolute value function 'fabs' given an argument of type 'long double' but
      has parameter of type 'double' which may cause truncation of value
      [-Wabsolute-value]
        if (ss != 0.0) ts = fabs((ss-oss)/ss);
                            ^
/Users/chris/repos/simbody/1/simbody/SimTKcommon/Polynomial/src/rpoly.cpp:311:29: note: 
      use function 'std::abs' instead
        if (ss != 0.0) ts = fabs((ss-oss)/ss);
                            ^~~~
                            std::abs
```

I'm really scared of editing `rpoly.cpp` because it uses `goto`'s. Are the `goto`'s affected by macros? Two possible fixes: ignore the warning or use `std::abs`.

**Comment by sherm1** [comment]
Every `fabs` in rpoly.cpp should be replaced by `std::abs`. As long as the regression tests pass afterwards that should be a harmless change (actually an improvement because the warning is correct). Please feel free to make a PR with that change.
