### ISSUE TITLE
Create DEPRECATED macro as a holdover until we support C++14

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#391]
For compilers that support this C++14 feature, we can use `[[deprecated]]` directly. For those that don't, we can use `#warning` maybe.

**Comment by sherm1** [comment]
The C++14 deprecated feature has support for a message to be issued -- we should make sure the macro supports that. Here is [some documentation](http://en.cppreference.com/w/cpp/language/attributes). Microsoft VS2013 does not support this but has something close described [here](https://msdn.microsoft.com/en-us/library/044swk7y.aspx) and also some kind of weird [#pragma](https://msdn.microsoft.com/en-us/library/c8xdzzhh.aspx).

**Comment by chrisdembia** [comment]
Thanks for the info.

**Comment by chrisdembia** [comment]
Fixed in #407.
