### ISSUE TITLE
Compiler version check for gcc incorrecly fails

### ISSUE THREAD

**Issue by elen4** [simbody/simbody#482]
I tried to compile Simbody on an Ubuntu 14.04 LTS machine, with gcc 4.8.4 installed, as checked with ``gcc --version``. Although the ``SIMBODY_REQUIRED_GCC_VERSION`` is 4.8.1, the check fails and issues a fatal error, because the version retrieved with the ``gcc -dumpversion`` command is in major.minor fomat, i.e., 4.8 ( https://bugs.launchpad.net/ubuntu/+source/gcc-4.8/+bug/1360404).
Setting ``SIMBODY_REQUIRED_GCC_VERSION`` to 4.8 in the main CMakeLists.txt fixes this issue for me.

**Comment by chrisdembia** [comment]
Thank you for reporting this.

Maybe we should try using the variable `CMAKE_CXX_COMPILER_VERSION` instead of using `gcc -dumpversion`

http://stackoverflow.com/questions/14933172/how-can-i-add-a-minimum-compiler-version-requisite

Could you quickly test if this also fixes the problem for you?

**Comment by elen4** [comment]
Hi Chris, yes, this works for me as I get the full major.minor.patch version. I am using CMake 2.8.12.2, but I think that this variable was introduced in CMake 2.8.9, so I guess you would need to bump up the minimum required version, since it currently is 2.8.8 for non-MSVC compilers

**Comment by chrisdembia** [comment]
Ah okay good point.

**Comment by chrisdembia** [comment]
Thanks for checking.

**Comment by Gjacquenot** [comment]
I have created a pull request to fix this.
I have not updated the CMake version. Maybe @chrisdembia , you want it to be updated?
We would move from 2.8.8 -> 2.8.10 for CMake

**Comment by chrisdembia** [comment]
Ubuntu 14.04 provides cmake 2.8.12.2, and we already require gcc 4.9.1, which Ubuntu 14.04 does not require. So I suppose it would be okay to change the required CMake version.

**Comment by chrisdembia** [comment]
I know this isn't directly related to this issue, but it would be good for us to clearly state the version(s) of Ubuntu that we support in the README.

**Comment by elen4** [comment]
Isn't the required gcc version 4.8.1? This is stated both in the README and in the main CMakeLists, and Ubuntu 14.04 complies with this

**Comment by chrisdembia** [comment]
Oh wow, good catch. Sorry about that. Yes, then the required version of Ubuntu is 14.04. Thanks, @elen4.

**Comment by sherm1** [comment]
Didn't we decide we have to require gcc 4.9 though, for regular expression support?

**Comment by chrisdembia** [comment]
Yes, you're right (sorry!); still, Ubuntu 14.04 provides 4.9.3.

**Comment by Gjacquenot** [comment]
@chrisdembia, @sherm1 , I think this issue can be closed!

**Comment by sherm1** [comment]
Can you verify and close please @elen4?

**Comment by elen4** [comment]
Well, the original issue was causing problems with gcc < 4.9, therefore increasing the minimum gcc version fixed it automatically :smile:, although it required a manual gcc update on my side.
Anyway, I like this version of the compiler version check better, and it's working for me. I would add information on how to update gcc for ubuntu 14.04 in the README, right now I only see it in the changelog

**Comment by sherm1** [comment]
Thanks, @elen4!
