### ISSUE TITLE
Describe how to get GCC 4.9 in Ubuntu 14.04 in the README

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#487]
@elen4 suggested this in #482. The CHANGELOG gives instructions; we should copy them over to the README.

**Comment by Gjacquenot** [comment]
I think one can find good instructions [here](http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu-14-04)

**Comment by chrisdembia** [comment]
Thanks Guillaume.

**Comment by Gjacquenot** [comment]
@elen4 : I have created a [fork](https://github.com/Gjacquenot/simbody) that contain documentation on how to install GCC 4.9 on Ubuntu.
Can you read and check the paragraph "Check the compiler version" in this [commit](https://github.com/Gjacquenot/simbody/commit/c11863e744dd1cf4f9464acec86ac39376120b44)?

**Comment by elen4** [comment]
Hi @Gjacquenot , I used a slighty different syntax for some commands (I "configured" separately gcc and g++), but I think these work the same. I also called ```sudo update-alternatives --remove-all gcc``` and ```sudo update-alternatives --remove-all g++``` before the ```sudo update-alternatives --install``` command, but I do not think this is necessary.
So it looks good, **but** you need to add the PPA with newer gcc releases to your system, with
```sudo add-apt-repository ppa:ubuntu-toolchain-r/test``` (this should go before line 256)

**Comment by Gjacquenot** [comment]
Hi @chrisdembia , I have created a PR to describe how to get GCC 4.9 in Ubuntu 14.04 in the README.
Could you have a look?

**Comment by chrisdembia** [comment]
Thanks for submitting that PR. I have made comments there.

**Comment by chrisdembia** [comment]
Thank you @elen4 for taking a look also.

**Comment by Gjacquenot** [comment]
Hi @chrisdembia , this issue can now be closed!

**Comment by chrisdembia** [comment]
Great. Thank you
