### ISSUE TITLE
Hard-code relative path from SimTKsimbody library to simbody-visualizer

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#512]
Right now, we hard-code a full path to the installed location of the simbody-visualizer; see https://github.com/simbody/simbody/pull/64. It might be better to hard-code a relative path from the SimTKsimbody library file to the simbody-visualizer executable. This would allow us to relocate the installation and still find the visualizer without setting environment variables.

**Comment by moorepants** [comment]
Here is a use case: https://github.com/conda-forge/staged-recipes/pull/1076#issuecomment-233785977

With conda we have to overwrite the hardcoded path to make things relocatable.

**Comment by chrisdembia** [comment]
This has been addressed for most UNIX systems; #559
