### ISSUE TITLE
Public interface for calcConstraintAccelerationErrors()

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#514]
Right now, there is an internal method `SimbodyMatterSubsystemRep::calcConstraintAccelerationErrors()`; this method is not available to Simbody users. I'd like to add a method `SimbodyMatterSubsystem::calcConstraintAccelerationErrors()`. This would be very similar to the presence of `SimbodyMatterSubsystemRep::calcBodyAccelerationFromUDot()` and `SimbodyMatterSubsystem::calcBodyAccelerationFromUDot()`. For example, the user method would accept non-contiguous input/output Vectors.

I plan to add a test case in `TestConstraints`, based on some of the tests in `TestMassMatrix` and on `testConstraintMatrices()` in `TestConstraints`.

I plan to use this method in OpenSim alongside computing an implicit form of the dynamics.

**Comment by chrisdembia** [comment]
Right now, the internal `calcConstraintAccelerationErrors()` takes `A_GB`, `udot`, and `qdotdot` as arguments. What do you think about having the public variant just take `udot` and use it to compute `A_GB` from the public `calcBodyAccelerationFromUDot()`, and compute `qdotdot` from the public `calcQDotDot()`?

**Comment by sherm1** [comment]
I see there is already a method `Constraint::calcAccelerationErrorFromUDot(state,udot)`. But I went to look at the implementation and saw this:
```c++
Vector Constraint::calcAccelerationErrorFromUDot(const State&, const Vector& udot) const {
    SimTK_THROW1(Exception::UnimplementedMethod, "Constraint::calcAccelerationErrorFromUDot");
}
```
So I guess that's not very helpful!

**Comment by sherm1** [comment]
> What do you think about having the public variant just take udot and use it to compute A_GB from the public calcBodyAccelerationFromUDot(), and compute qdotdot from the public calcQDotDot()?

Yes, that's definitely the way to do it. The A_GB, qdotdot, and udot must all be consistent so you don't want to trust users to supply those.

A few testing ideas:
- use forward dynamics on a constrained system to calculate udots; save those; then using a different State object that has been realized only to Velocity stage, call your new method with (a) zero udots and verify you get non-zero errors, and (b) the saved udots and verify you get zero errors.
- the acceleration error equations are G udot - bias(t,q,u) = 0. So you should be able to use your method to calculate G, which Simbody will also do for you with the calcG() method. You would call your method once with udot=0 to calculate -bias, then m times with one of the udots 1 and the rest 0 to pick up one column of G.

This is a great addition to Simbody -- thanks!

**Comment by chrisdembia** [comment]
> So I guess that's not very helpful!

❗  ->  😞 

Thank you for those testing ideas.

I'll proceed on this now.
