### ISSUE TITLE
README typo [hyperminor issue]

### ISSUE THREAD

**Issue by kidzik** [simbody/simbody#531]
In the ubuntu installation part there is

    sudo apt-get install libsimbody-dev libsimbody-doc

should be

    sudo apt-get install libsimbody-dev simbody-doc

**Comment by scpeters** [comment]
We host Ubuntu trusty packages at [packages.osrfoundation.org](http://packages.osrfoundation.org/gazebo/ubuntu-stable/pool/main/s/simbody/), and at the time they were built it was called `libsimbody-doc`. Now simbody is in the [official Ubuntu repositories](http://packages.ubuntu.com/source/xenial/simbody) and it is called `simbody-doc`, as you say.

**Comment by kidzik** [comment]
Sure, I didn't want to complain, I am just in the process of getting into OpenSim and trying tutorials so when I found a minor confusing type I decided to report/note here.

**Comment by chrisdembia** [comment]
Nice catch @kidzik. Thanks for the background, @scpeters. I've submitted a PR to fix this.

**Comment by scpeters** [comment]
Yes, thanks for posting @kidzik !
