### ISSUE TITLE
Const in HandleEvent definition

### ISSUE THREAD

**Issue by YuriOsokin** [simbody/simbody#547]
I try to use another library for the control of the dynamical system, which I simulate in SimBody. I created the PeriodicEventHandler, which applies controlled force to the joints. The problem is that the HandleEvent callback has const in its declaration. The library I use does not have const method in it. So, I have a variety of problems with it. 
For example:
HandleEvent (..) const {
  Joint.SetForce(net.predict(state.GetPosition()));
}
net.predict() is not const.

What is the preferred solution for the problem? And could you explain, please, why the HandleEvent method is const?
Thank you.

**Comment by chrisdembia** [comment]
This question is more appropriate for the Simbody forum. Therefore, I am closing this issue; if we determine that there is indeed some bug somewhere (doesn't seem like it yet), we can reopen the issue.

From the [documentation of `handleEvent()`](https://github.com/simbody/simbody/blob/master/SimTKcommon/Simulation/include/SimTKcommon/internal/EventHandler.h#L55):

> It is given a State which 
    describes the system at the time when the event occurs, and it is permitted
    to modify any aspect of the state except the time.

That is, handling an event can involve changing the values of state variables, but should not alter the System itself (e.g., mass properties, number of bodies/joints, etc.).
