### ISSUE TITLE
Visualizer crashes on some sample examples

### ISSUE THREAD

**Issue by nikhil-bidgely** [simbody/simbody#562]
Observed this bug this bug while using "ExampleContactPlayground" on 16.04 installed in virtual box. Simbody was installed using conda.

Other related issues: 
[https://github.com/simbody/simbody/issues/155](url)
[https://github.com/conda-forge/simbody-feedstock/issues/15](url)

**Comment by moorepants** [comment]
Duplicate of https://github.com/conda-forge/simbody-feedstock/issues/15
