### ISSUE TITLE
States cannot be used with different Systems

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#567]
When we added support for parallel calculation of forces, we coupled State objects to the System they came from, by caching `Force*`s from the System in the State (see [here](https://github.com/simbody/simbody/blob/master/Simbody/src/GeneralForceSubsystem.cpp#L643) and [here](https://github.com/simbody/simbody/blob/master/Simbody/src/GeneralForceSubsystem.cpp#L713)).  This prevents users from easily using a state from one instance of a System with a different but identical instance of the System.

Related: https://github.com/opensim-org/opensim-core/issues/1455, https://github.com/opensim-org/opensim-core/issues/1785

**Comment by sherm1** [comment]
Great find -- that's so wrong! Probably those pointers should have been ForceIndex values instead?

**Comment by chrisdembia** [comment]
> Probably those pointers should have been ForceIndex values instead?

It'd be great if that will work.
