### ISSUE TITLE
std::memcpy does not work with ADOL-C type adouble

### ISSUE THREAD

**Issue by antoinefalisse** [simbody/simbody#574]
We are trying to bring automatic differentiation to Simbody using ADOL-C. We have observed that std::memcpy does not work with adoubles, since this will copy the location in the tape and results in a shallow copy rather than a deep copy. Instead of using std::memcpy, we have seen that we could use std::copy which works with adoubles. We read that std::copy would delegate to std::memcpy when it is appropriate. We therefore would like to change the calls to std::memcpy by std::copy.

**Comment by sherm1** [comment]
:+1: Good idea!
