### ISSUE TITLE
Replace pthread with c++11 threading support

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#584]
Pthreads for windows has an LGPL license. In order to avoid that license, we should replace this library with C++11's std::thread, etc.

I've already started to work on this, and I am a little more than halfway through.

@sherm1 do you think you would you accept a PR (or PRs) for this?

Related: #422.

- [x] AtomicInteger
- [x] ThreadLocal
- [x] ParallelWorkQueue
- [x] ParallelExecutor
- [x] VisualizerProtocol
- [x] Visualizer_InputListener
- [x] Visualizer
- [x] simbody-visualizer
- [x] Delete pthreads for windows files.
- [x] Update changelog.

**Comment by sherm1** [comment]
Definitely! I would love to get rid of pthreads altogether. It has other problems besides the license.

**Comment by chrisdembia** [comment]
Great.

**Comment by chrisdembia** [comment]
I've updated the top comment of this issue with a list of steps.

**Comment by chrisdembia** [comment]
I have a branch, `replace_pthreads`, in which the removal of pthreads is nearly complete (the only thing left is to actually remove the pthreads files for Windows). I've tested fairly thoroughly on Mac, but not on other platforms. On Linux, I am getting the following error (note to self):

```
Visualizer listenerThread: unrecoverable error:
SimTK Exception thrown at VisualizerProtocol.cpp:179:
  Error detected by Simbody method VisualizerProtocol: An attempt to read() 2 bytes from pipe 5 failed with errno=9 (Bad file descriptor).
  (Required condition 'retval!=-1' was not met.)

```

My plan is to merge small parts of `replace_pthreads` into the `feature_replace_pthreads` branch until the removal is complete.
