### ISSUE TITLE
Method deprecation not working on Windows any more

### ISSUE THREAD

**Issue by sherm1** [simbody/simbody#607]
Simbody's `DEPRECATED_14()` macro is not functioning on Windows any more. I believe this is because warning 4996 has been disabled globally. That should only be disabled locally with pragma push/pop so that we can mark methods deprecated.

@chrisdembia do you remember why 4996 got removed globally?

**Comment by chrisdembia** [comment]
Uh oh. This warning got removed when we replaced `memcpy` with `std::copy` this summer (https://github.com/simbody/simbody/blob/a899db7be06ff3ae70c4b60a8922e62b5b6a8a63/CMakeLists.txt#L456). I think @antoinefalisse tried disabling the warning in a more local manner but MSVC wouldn't let us.

See here for more information: https://stackoverflow.com/questions/42003997/c-array-copy-showing-errors-in-vc

**Comment by sherm1** [comment]
OK, thanks. I'll see if I can deal with it locally.
