### ISSUE TITLE
Limit the MobilizedBody motion

### ISSUE THREAD

**Issue by YuriOsokin** [simbody/simbody#619]
Hello,

I want to limit the MobilizedBody motion. For example, to limit the Pin to angles of -1 rad to 1 rad. I did not find any simple way to do it, but to write an EventHandler, and set the force on the Pin, such, that will not allow the motion above the limits. The event is triggered when the angle is greater then 1 rad, and the force is set as exponent of current Pin angle minus limit angle.
Is this a right approach, or there is a build-in way to limit the motion?

Thanks, Yuri

**Comment by sherm1** [comment]
You can use a "stop" force element to limit joint motion. [MobilityLinearStop](https://simbody.github.io/simbody-3.5-doxygen/api/classSimTK_1_1Force_1_1MobilityLinearStop.html) is a built-in one.
