### ISSUE TITLE
Doxygen for HuntCrossleyContact contains mangled equations

### ISSUE THREAD

**Issue by tkuchida** [simbody/simbody#623]
https://simtk.org/api_docs/simbody/3.5/classSimTK_1_1HuntCrossleyContact.html#details

![](https://user-images.githubusercontent.com/4203505/36510741-00346696-1719-11e8-997d-ba87974fa8ab.png)

**Comment by chrisdembia** [comment]
The equations look better here: https://simbody.github.io/simbody-3.6-doxygen/api/classSimTK_1_1HuntCrossleyForce.html

**Comment by tkuchida** [comment]
Thanks; I didn't realize this had been fixed.
