### ISSUE TITLE
Release Simbody 3.6.1

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#634]
OpenSim 4.0 will be released in about 3 weeks. It would be great if the OpenSim release contained https://github.com/simbody/simbody/pull/633. I'd like to make a Simbody 3.6.1 release to include the #633.

- [x] merge #633 into the `simbody-3.6` branch.
- [x] update changelog
- [x] in README.md, replace "3.6" with "3.6.1"
- [x] update release date of 3.6.1 in the changelog.
- [x] make 3.6.1 release (tag)
- [x] announce release on forum

**Comment by sherm1** [comment]
:+1:

**Comment by chrisdembia** [comment]
I've gone ahead and finished the tasks above. The tip of the `simbody-3.6` branch is now the `Simbody-3.6.1` tag.

**Comment by sherm1** [comment]
Great! Thanks, Chris.
