### ISSUE TITLE
Python interface: Directly working with state's Y value leads to crash

### ISSUE THREAD

**Issue by janEbert** [simbody/simbody#638]
Using an OpenSim environment in Python, the program crashes when attempting to do anything with  `SimTK::State`'s `Y` value except for assigning it.

Setup:
```python
from osim.env import ProstheticsEnv
env = ProstheticsEnv(visualize=False)
env.reset()
```
What works:
```python
state = env.osim_model.get_state()
print(state.getY())

y = env.osim_model.get_state().getY()
```
What does not work:
```python
print(env.osim_model.get_state().getY())
list(env.osim_model.get_state().getY())
```

I am on Windows 10 using the latest version of OSim (with Python 3.6.1) and followed the installation instructions to a T.

Sorry if this belongs in the [OSim-RL](https://github.com/stanfordnmbl/osim-rl) repository.

**Comment by chrisdembia** [comment]
Thanks for reporting this. Do you have a backtrace?

**Comment by janEbert** [comment]
There is no backtrace, the Python process crashes ("Windows is searching for an error") and the command prompt returns to normal when I close the process. Sorry for not mentioning that.

**Comment by chrisdembia** [comment]
I'm a little confused: did you run the "code that does not work" after having already run "what works"? Can you share the complete code that works and the complete code that does not work?

> Sorry if this belongs in the OSim-RL repository.

The best place for this is https://github.com/opensim-org/opensim-core, because that's where the bindings for OpenSim and Simbody are created.

**Comment by chrisdembia** [comment]
@janEbert, let's continue discussion at https://github.com/opensim-org/opensim-core/issues/2214
