### ISSUE TITLE
Is Explicitly Setting CMP0003 and CMP0005 Necessary?

### ISSUE THREAD

**Issue by artin-f** [simbody/simbody#662]
Two CMake policies are explicitly set to `NEW` here:
https://github.com/simbody/simbody/blob/43c2645c634bc93488deab52da231708b4654a9f/CMakeLists.txt#L21-L24

Both `CMP0003` and `CMP0005` were added in CMake version `2.6` [[ref]](https://cmake.org/cmake/help/v3.13/manual/cmake-policies.7.html#manual:cmake-policies(7)).  Since Simbody requires CMake version `2.8.10` and above, both policies are set to `NEW` by default.  Therefore, explicitly setting them seems unnecessary.

The above code doesn't cause any issues in Simbody operation, but removing it will improve readability and maintainability a little bit.

**Comment by artin-f** [comment]
Great, thank you for your feedback.  You can assign this issue to me.  I'll open a PR shortly.

**Comment by sherm1** [comment]
Thanks, Artin!
