### ISSUE TITLE
Smooth Contact Model

### ISSUE THREAD

**Issue by antoinefalisse** [simbody/simbody#666]
Hi @sherm1 and @chrisdembia,

@gilserrancoli and I have been using a smooth approximation of the Hunt-Crossley contact model available in Simbody for our applications (OpenSim-based predictive simulations of movements). The rationale for using such smooth model was the use of gradient-based optimization that requires twice-continuously differentiable models. 

We believe this smooth model could be useful for the community, in particular with software like Moco, and therefore propose to merge it into Simbody.

**Comment by sherm1** [comment]
Resolved by #667.
