### ISSUE TITLE
Constraint::Custom::Implementation override wrong function when implementing acceleration constraint

### ISSUE THREAD

**Issue by dpkong** [simbody/simbody#669]
I define a acceleration constraint implementation inherited from Constraint::Custom::Implementation
I am sure I initialize Implementation(matter, 0, 0, 1) and override the calcAccelerationErrors function
But it still ask me to override the calcVelocityDotErrors because in runtime it is called and virtual function was called.
After I override calcVelocityDotErrors in the acceleration constraint implementation, it works.
[PrescribedAcc.txt](https://github.com/simbody/simbody/files/3341072/PrescribedAcc.txt)

**Comment by sherm1** [comment]
@dpkong Yun, can you verify that the change in PR #670 fixes the problem you reported here?
