### ISSUE TITLE
macOS Catalina: Visualizer is 1/4 size

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#674]
On macOS Catalina, the simbody-visualizer only takes up 1/4 of the window:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/846001/67166439-46a42900-f344-11e9-98ac-fae7dd7a6a6e.png">

This might be related: https://github.com/redeclipse/base/issues/920

Given that freeglut is deprecated on macOS, we could also consider using Metal or an abstraction layer:

- https://developer.apple.com/videos/play/wwdc2018/604/?time=430
- https://developer.apple.com/documentation/metal/migrating_opengl_code_to_metal
- https://github.com/LukasBanana/LLGL
- https://github.com/KhronosGroup/MoltenVK

**Comment by chrisdembia** [comment]
@peastman do you have any suggestions?

**Comment by peastman** [comment]
No idea.  When you resize the window does it remain 1/4 of the window?

**Comment by scpeters** [comment]
Are you using a laptop with a retina screen?

**Comment by chrisdembia** [comment]
> When you resize the window does it remain 1/4 of the window?

Yes

> Are you using a laptop with a retina screen?

Yes. This happens on both a MacBookPro and an iMac.

**Comment by peastman** [comment]
Sounds like it could be a bug in resolution scaling.  On the issue that referenced this one just above, someone suggested https://github.com/redeclipse/base/commit/6dce7794981eea639d16b7f3a6809f1c0c889a46 as a possible fix.

**Comment by chrisdembia** [comment]
Thank you @peastman . I'll try that when I get a chance.

**Comment by chrisdembia** [comment]
- https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/EnablingOpenGLforHighResolution/EnablingOpenGLforHighResolution.html#//apple_ref/doc/uid/TP40001987-CH1001-SW4
- https://github.com/SFML/SFML/issues/353

We can either make a .app and set NSHighResolutionCapable to false, or we can edit the OpenGL functions taking pixels to use 2x values and have a higher-res visualizer.

I think the issue introduced by Catalina is that the OS now assumes taht NSHighResolutionCapable is true.

**Comment by chrisdembia** [comment]
Magnum seems like a promising library: https://github.com/mosra/magnum. It's used by DART.

**Comment by chrisdembia** [comment]
Here is how SDL finds the "backing scale factor": https://github.com/spurious/SDL-mirror/blob/60cae8d8affb61ec661f1eb5d5be5fed6a3c239d/src/video/cocoa/SDL_cocoaopengl.m#L362-L383

I don't know how we'd get access to the NSView when using GLUT.
