### ISSUE TITLE
Please correct installation instructions on your website

### ISSUE THREAD

**Issue by yurivict** [simbody/simbody#675]
Many systems have packages for simbody (see here https://repology.org/project/simbody/versions), but your website asks users to build from source, which is much more difficult: https://simtk.org/projects/simbody/

Please correct the recommendations and ask users to install from a package where they are available.

Please also add ```FreeBSD``` to the list of supported systems because ```simbody``` package can be easily installed there with this command: ```pkg install simbody```.

**Comment by sherm1** [comment]
This was fixed in PR #680 for Simbody release 3.7 (and master). I'll close this now. Please open a new issue (or better, PR) if there are further changes you would like to see @yurivict.
