### ISSUE TITLE
Inverse Kinematics fail

### ISSUE THREAD

**Issue by livrou** [simbody/simbody#678]
So I am trying to run inverse kinematics and when I put in any time range (0 to 1.5), (0.0083 to 7.666) etc, it won't register that there is a final time and then fails since the final time (0)  is before the start time. Even when I edited it in the text editor and wrote: <time_range> 0.008333 12.333333</time_range>, then loaded it into the IK tool it showed the final time was 0.

**Comment by chrisdembia** [comment]
I think you might find more success obtaining help by posting your issue to [OpenSim's forum](http://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB).
