### ISSUE TITLE
Release Simbody 3.7

### ISSUE THREAD

**Issue by chrisdembia** [simbody/simbody#679]
@sherm1 can I prepare a Simbody 3.6.2 release that includes the macOS Catalina fix (#676)?

- [x] update changelog
- [x] in README.md, replace "3.6" with "3.7"
- [x] check that README.md is up to date
- [x] update version number for user guide and advanced programming guide 
- [x] check theory manual
- [x] post doxygen on a new simbody repository (simbody-<version>-doxygen)
- [x] update release date of 3.7 in the changelog.
- [x] make 3.7 branch
- [x] make 3.7 release (tag)
- [ ] update master branch to 3.8
  - [x] add "3.8" section to CHANGELOG.md.
- [x] update github.com/simbody/simbody.github.io/index.html and github.com/simbody/simbody.github.io/latest/index.html.
- [x] announce release on forum

**Comment by sherm1** [comment]
(Fixed comment to read 3.6.2) -- yes definitely, thanks!

**Comment by chrisdembia** [comment]
Oops; thanks for the correction. Great.

**Comment by chrisdembia** [comment]
Actually, @sherm1 , given the new smooth contact model, what about a 3.7 minor release instead?

**Comment by sherm1** [comment]
Makes sense. Would need to update the release notes a little to advertise.

**Comment by chrisdembia** [comment]
Will do.

**Comment by chrisdembia** [comment]
I've started the release process, and I hope to finish it on Monday.

I'd like to restructure how we handle hosting doxygen by putting it all at `simbody.github.io`, using the new repo I just created. https://github.com/simbody/simbody.github.io. I'll update the links to doxygen that are in the user's guide, etc.

**Comment by chrisdembia** [comment]
Okay, doxygen for all versions is now at https://simbody.github.io.

**Comment by sherm1** [comment]
Doxygen looks good on github.io. Can you say why that's better than the old way?

**Comment by chrisdembia** [comment]
With the old way, we would need to create a new repository and edit the `simbody-latest-release` repository. Now, we can edit one repository. The new URL is shorter. Lastly, the landing page allows users to select the version for which they want documentation; before, users would need to navigate to a separate URL on their own.

If you prefer the old way, I can undo the changes.

**Comment by sherm1** [comment]
Nope, I was just wondering what the reason for the change was. Thanks!

**Comment by chrisdembia** [comment]
@sherm1, I created a release for 3.7 (https://github.com/simbody/simbody/releases/tag/Simbody-3.7) and announced the release in the forum (https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=47&t=11304&p=0&start=0&view=).

To finish this issue, I created a PR to update the master branch after the 3.7 release.
