### ISSUE TITLE
README example contains a horizontal plane

### ISSUE THREAD

**Issue by adamkewley** [simbody/simbody#696]
Not a fatal issue, but just something I noticed when going through the docs.

If I compile the example in the README ("Here's some code to simulate and visualize a 2-link chain") and run it, I'm getting something that looks like this:

![Screenshot from 2020-06-09 10-45-27](https://user-images.githubusercontent.com/4730570/84133066-93a54e80-aa3e-11ea-9560-b2d92069f569.png)

I'm using the simbody that's built for OpenSim (tag = `Simbody-3.7`), so it's a bit older than what's in the master branch (so this might've been fixed already).

**Comment by adamkewley** [comment]
I've PRed a possible fix for this:

https://github.com/simbody/simbody/pull/697

**Comment by sherm1** [comment]
Fixed by #697.
