### ISSUE TITLE
Question about Simbody pre-processing/input file/CPP... for simulation

### ISSUE THREAD

**Issue by yumianhuli2** [simbody/simbody#722]
Does Simbody have a pre-processing module to generate the simulation input file, and then perform the simulation by parsing the simulation input file? Or Simbody currently only providing the ability to write CPP files for simulation?
Thank you！

**Comment by sherm1** [comment]
You have to write a C++ main program. There is an example (Gazebo2Simbody) that reads an .sdf file -- you could modify that if you want to try making a generic main program that can be driven from an external file.
