### ISSUE TITLE
About 2d/3d constraint library

### ISSUE THREAD

**Issue by yumianhuli2** [simbody/simbody#728]
Hello！
What C++ code files of simbody are associated with the kinematic/dynamics 2d/3d constraint library？
Thank you！

**Comment by sherm1** [comment]
In the [Simbody/src](https://github.com/simbody/simbody/tree/master/Simbody/src) directory there is a set of files with names beginning with `Constraint_`, for example:
[Constraint_PointOnPlaneContact.cpp](https://github.com/simbody/simbody/blob/master/Simbody/src/Constraint_PointOnPlaneContact.cpp)

For each of those there is a public header file in [Simbody/include/simbody/internal](https://github.com/simbody/simbody/tree/master/Simbody/include/simbody/internal)

and a private implementation header in Simbody/src named the same but with "Impl" added.

Is that what you are looking for?

**Comment by yumianhuli2** [comment]
> In the [Simbody/src](https://github.com/simbody/simbody/tree/master/Simbody/src) directory there is a set of files with names beginning with `Constraint_`, for example: [Constraint_PointOnPlaneContact.cpp](https://github.com/simbody/simbody/blob/master/Simbody/src/Constraint_PointOnPlaneContact.cpp)
> 
> For each of those there is a public header file in [Simbody/include/simbody/internal](https://github.com/simbody/simbody/tree/master/Simbody/include/simbody/internal)
> 
> and a private implementation header in Simbody/src named the same but with "Impl" added.
> 
> Is that what you are looking for?

It looks like it is, but it would be a lot easier to understand if you had a diagram for each constraint. Thank you！！
