### ISSUE TITLE
Setting output precision for String::String(const T& t)

### ISSUE THREAD

**Issue by fcanderson** [simbody/simbody#758]
@sherm1 
I hope you are doing well.  I took a break from coding for a few months, but I'm back to it now.  I have a few minor tweaks that I'd like to make to Simbody.  Before I submit a PR, I'd like to check with you to see how you'd like me to go about that. 

First up are some almost-one-liner changes I'd like to make in String.h and in Xml.h.  I've also made some minor changes to class ExponentialSpringForce, but I will address those after this output precision issue is resolved.

------
Some background
------
In OpenSim, I've implemented class StatesDocument, which follows through on the planned roadmap capability of serializing ALL states (continuous, regular discrete, auto-update discrete, modeling option). Currently, OpenSim employs no systematic approach for serializing/deserializing discrete states. When they are encountered (e.g., as in the input controls for a simulation), they are handled on a case-by-case basis usually by using a separate file or by treating them as Properties of an OpenSim::Object.  I ran into trouble when bringing my exponential spring contact class into OpenSim, as class ExponentialSpringForce has several discrete states and auto-update discrete states (i.e., the coefficients of friction, elastic anchor point, and sliding state).  It was untenable to handle the auto-update discrete states with Properties, and creating a separate file to store the time histories would have been cumbersome and complex.  With class StatesDocument in place, things are streamlined.  The time histories of all states are stored in a single XML file with a ".ostates" file extension by convention.  In addition, a StateDocument is able to accommodate a range of common data types (e.g., ```Array_<int>, Array_<bool>, Array_<double>, Array_<Vec3>, Array_<Vec4>```, etc.).

I used class SimTK::Xml to handle all the XML-related stuff, and StatesDocument fell out quite naturally as a result. There was only one feature that I couldn't figure out how to specify without a code change in Simbody:  **output precision**.  That is, how many significant figures are written out.  For many situations lossless conversion to a String is needed, but in some situations (e.g., debugging or graphing simulation results) 20 digits are likely overkill and reducing file size would be helpful.

The current call chain in Simbody for converting a value to a String as implemented in SimTK::Xml follows below.  I'll take the case of a value of type of ```Array_<Vec3>``` just to make things concrete.  Indentions preceded by a "-->" indicate the next level down in the call chain.
```
// In calling code
Array_<Vec3> someValue;   \\ initialized somehow
someXmlElement.setValueAs<Array_<Vec3>>(someValue);

--> // In class SimTK::Xml::Element
    void setValueAs(const Array_<Vec3>& value) {
        setValue(String(value));
    }

    --> // In class SimTK::String in the overloaded constructor
        String::String(const Array_<Vec3>& t) {
            std::ostringstream os;
            *this = stringStreamInsertHelper(os, t, true).str();
        }
```
Here, the creation of the string that will ultimately be written to file will have the default global ```ostream``` precision, which is 6 (at least on Windows in Visual Studio 19).  There may be some way to manage the global default precision.  Even if so, however, I think taking steps to alter global output precision and then return it to some agreed upon baseline value would be messy. 

------
Changes I'd like to merge.
------
I'd like to add a `precision` argument, which has a default value of ```SimTK::LosslessNumDigitsReal```, to both Xml::Element::setValueAs(const T& value) and to String::String(const T& value).  So, the modified code would be

```
// In calling code
int PRECISION = 8;   \\ Just an arbitrary example value.  PRECISION in CAPS just to stand out here.
Array_<Vec3> someValue;   \\ initialized somehow
someXmlElement.setValueAs<Array_<Vec3>>(someValue, PRECISION);
// Alternatively, the following call without the precision argument yields lossless conversion to a string.
// someXmlElement.setValueAs<Array_<Vec3>>(someValue);

--> // In class SimTK::Xml::Element
    void setValueAs(const Array_<Vec3>& value, int PRECISION=SimTK::LosslessNumDigitsReal) {
        setValue(String(value, PRECISION));
    }

    --> // In class SimTK::String in the overloaded constructor
        String::String(const Array_<Vec3>& t, int PRECISION=SimTK::LosslessNumDigitsReal) {
            std::ostringstream os;
            os << std::setprecision(PRECISION);  // Other than adding PRECISION as an arg, the only new line of code
            *this = stringStreamInsertHelper(os, t, true).str();
        }
```
A nice feature of this approach is that the output precision is only modified on the local ```ostringstream``` object; any modification of precision only affects the construction of the string in question.

I have implemented the above changes.  All existing Simbody regression tests pass.  In OpenSim, class StatesDocument is functioning as intended, and the control of output precision has been straight forward. 

------
 Issues / Questions
------
1. First, is there already a way to control output precision in Simbody for ```String::String(const T& t)``` that I did not find but should be using? 
2. Default Precision. Should the default precision be ```SimTK::LosslessNumDigitsReal```? Choosing this increased precision could alter the output that folks get. When debugging, for example, unless they explicitly specify a smaller precision, folks would get 20 digits, instead of only 6. I note here that the construction of Strings via other overloaded constructors appears to make the same choice.  That is, in the absence of a specified output format, max precision is what is delivered.
3. Testing.  Should I enhance regression testing for classes SimTK::String and SimTK::Xml by adding some tests that focus on output precision?  Or, are these changes basic enough that additional tests are not needed? <**bowing head in prayer that additional tests are not needed**>
4. Trailing White Space.  Both String.h and Xml.h have many lines with trailing white spaces.  Should I first submit a PR with the trailing white spaces removed so that the substantive changes are not camouflaged by zillions of incidental edits? I could leave the trailing white spaces in String.h and Xml.h, but that would actually be a little bit more of a pain because in my versions of the files the trailing whitespaces have already been removed.

Thanks,
Clay

**Comment by sherm1** [comment]
Hi, Clay! This seems like a good fix, thanks. My first thought is -- why not just change the output to lossless and _not_ add a precision parameter? If there is no immediate need for reduced precision, let's not add the extra complexity. It could always be added later if a necessary use case is discovered. I don't think reduced file size is a compelling need.

With no additional parameter, I don't think a new unit test would be required. With an API change, I do think a small test would be required to ensure that it works and keeps working in the future.

Regards, Sherm

**Comment by fcanderson** [comment]
Sherm, thanks for the response.  What you suggest { just changing the output to lossless always } would be simplest.  And, as you say, it can change later pretty simply if a need arises.

Do you care about how I deal with the trailing whitespace in String.h?

I am inclined to do two PRs:
PR1 to get rid of the trailing whitespace in String.h (and perhaps also Xml.h), and
PR2 to make the output precision change to lossless.

**Comment by sherm1** [comment]
Two PRs would be ideal, thanks.

**Comment by fcanderson** [comment]
#776 and #779 add the capacity to convert numerical types to ```SimTK::String```s and ```Xml::Element``` values.
