### ISSUE TITLE
Simbody Visualization not working on MacOS 

### ISSUE THREAD

**Issue by rutgerluinge** [simbody/simbody#777]
Hi,

I am using Simbody visualization in combination with Opensim. I can get the visualization to work on Linux and Windows however I am encountering problems on MacOS.

It is installed using the following command using a Conda environment:
`conda install -c opensim-org -c conda-forge opensim simbody
`

The following issue is encountered:

"RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': SimTK Exception thrown at VisualizerProtocol.cpp:167:
 Error detected by Simbody method VisualizerProtocol::ctor(): Unable to spawn executable 'simbody-visualizer' from directories: "

It seems to be an easy problem to solve, however I can not find a solution. Hopefully someone can help me.

**Comment by sherm1** [comment]
You should ask this question on the OpenSim forum or GitHub page rather than here on Simbody.
