### ISSUE TITLE
Visaulization

### ISSUE THREAD

**Issue by Giopestri01** [simbody/simbody#784]
![Screenshot (976)](https://github.com/simbody/simbody/assets/153372389/907e7285-9a73-4d50-bbe4-56dca516137a)
I tried to visualize an OpenSim model moving and I cannot see on the ground. 
Can anyone help me?

**Comment by sherm1** [comment]
Please post your question to the OpenSim forum [here](https://simtk.org/plugins/phpBB/indexPhpbb.php?f=91).
